name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure this matches the Python version you want to use

    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatchling
        python -m pip list  # Debug: list installed packages

    - name: Debug Python environment
      run: |
        which python
        python -m site
        python -m pip list

    - name: Build and publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m hatch build
        python -m hatch publish --username=__token__ --password=$PYPI_TOKEN
      
