name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatchling
    - name: Build and publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        hatch build
        hatch publish --username=__token__ --password=$PYPI_TOKEN
