name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full git history and all files are checked out

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: List files in the directory
      run: ls -la  # Debugging step to verify files

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch hatchling

    - name: Build and publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        hatch build
        hatch publish --username=__token__ --password=$PYPI_TOKEN
