name: Publish to PyPI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Updated to v3
    - name: Set up Python
      uses: actions/setup-python@v4 # Updated to v3
      with:
        python-version: '3.x'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Build and publish to PyPI
      working-directory: ./chip/chippy_ai
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry build
        poetry publish
